"""Compile the HLSL embedded in native/gpu_compute.cpp with the Windows D3D compiler.

The build embeds the bytecode in the DLL so the app does not compile shaders at runtime.
"""
import ctypes as ct
import re
from pathlib import Path

SOURCE = Path(__file__).resolve().parents[1]/'native/gpu_compute.cpp'
# D3DCOMPILE_OPTIMIZATION_LEVEL3 | D3DCOMPILE_IEEE_STRICTNESS, as the runtime fallback in gpu_compute.cpp.
FLAGS = (1 << 15) | (1 << 13)


def sources(text=None):
    """{'toneShader': hlsl, ...}: the shared 'common' block prefixed to every shader body."""
    blocks = dict(re.findall(r'static const char\* (\w+)=R"\((.*?)\)";', text or SOURCE.read_text(encoding='utf-8'), re.S))
    common = blocks.pop('common')
    shaders = {name: common+body for name, body in blocks.items()}
    # Variant for devices with doubles: numpy-exact division in the point colour weights.
    shaders['colorShaderExact'] = '#define EXACT_DIVISION 1\n'+shaders['colorShader']
    return shaders


def _blob(blob):
    vtable = ct.cast(ct.cast(blob, ct.POINTER(ct.c_void_p))[0], ct.POINTER(ct.c_void_p))
    pointer = ct.WINFUNCTYPE(ct.c_void_p, ct.c_void_p)(vtable[3])(blob)
    size = ct.WINFUNCTYPE(ct.c_size_t, ct.c_void_p)(vtable[4])(blob)
    data = ct.string_at(pointer, size)
    ct.WINFUNCTYPE(ct.c_ulong, ct.c_void_p)(vtable[2])(blob)   # Release
    return data


def compile_shader(name, text):
    """Returns (bytecode or None, compiler messages)."""
    compiler = ct.WinDLL('d3dcompiler_47.dll')
    data = text.encode()
    code, errors = ct.c_void_p(), ct.c_void_p()
    result = compiler.D3DCompile(data, len(data), name.encode(), None, None, b'main', b'cs_5_0', FLAGS, 0,
                                 ct.byref(code), ct.byref(errors))
    messages = _blob(errors).decode('utf-8', 'replace') if errors else ''
    bytecode = _blob(code) if result >= 0 and code else None
    return bytecode, messages


def header(compiled):
    lines = ['// Generated by tools/build_native_gpu.py from native/gpu_compute.cpp. Do not edit.']
    for name, code in compiled.items():
        body = ','.join(str(b) for b in code)
        lines.append(f'static const unsigned char {name}Code[{len(code)}]={{{body}}};')
    return '\n'.join(lines)+'\n'
